apiVersion: v1
kind: PersistentVolume
metadata:
    name: service1-manual-pv
spec:
    accessModes:
    -
        ReadWriteOnce
    capacity:
        storage: 1Gi
    persistentVolumeReclaimPolicy: Retain
    gcePersistentDisk:
        pdName: manual-disk-1