apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: service1-pvc1
    namespace: service1
spec:
    accessModes:
    -
        ReadWriteOnce
    resources:
        requests:
            storage: 1Gi