apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        name: snappass-main
    name: snappass-main
    namespace: snappass
spec:
    replicas: 2
    
    selector:
        matchLabels:
          app: snappass-main
    template:
        metadata:
            labels:
                app: snappass-main
        spec:
            containers:
                -
                    name: snappass-main
                    image: us.gcr.io/kuber-276115/snappass:1.0
                    env:
                        - name: REDIS_HOST
                          value: snappass-redis
                    ports:
                        - containerPort: 5000