apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: snappass-v2-deploy
  namespace: snappass
spec:
  replicas: 10
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: snappass-main
  template:
    metadata:
      labels:
        app: snappass-main
    spec:
      containers:
        - name: snappass-v2
          image: docker pull us.gcr.io/kuber-276115/snappass:v2.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
  strategy:
    canary:
      canaryService: snappass-v2-deploy
      stableService: snappass-main
      maxSurge: "20%"
      steps:
        - setWeight: 20
        - pause: {}
        - setWeight: 20
        - pause:
            duration: 10s
        - setWeight: 40
        - pause:
            duration: 10s
        - setWeight: 40
        - pause:
            duration: 10s
