apiVersion: v1
kind: Service
metadata:
    name: snappass-redis
    namespace: snappass
spec:
    ports:
        -
            port: 6379
            targetPort: 6379
    selector:
        app: snappass-redis
