apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: snappass-rollout
  namespace: snappass
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: snappass-app
  template:
    metadata:
      labels:
        app: snappass-app
        version: v1.0.0
    spec:
      containers:
        - name: snappass-v2
          image: us.gcr.io/kuber-276115/snappass:1.0 # This image contain version 1 of Snappass
          imagePullPolicy: Always
          env:
            - name: REDIS_HOST
              value: snappass-redis
          ports:
            - containerPort: 5000
  strategy:
    canary:
      steps:
        - setWeight: 10 # First step of deployment is shifting 10% of traffic to Canary service
        - pause:
            duration: 10m
      canaryService: snappass-stable-service # required. This service will forward traffic to v1.0 pods
      stableService: snappass-canary-service # required. This service will forward traffic to v2.0 pods
      # Integration with Istio vertual service
      trafficRouting:
        istio:
          virtualService:
            name: snappass-virtual-service # Virtual Service name required
            routes:
              - snappass-route # At least one route in virtual service is required. This is the route for Snappass traffic
---
apiVersion: v1
kind: Service
metadata:
  name: snappass-stable-service
  namespace: snappass
spec:
  # type: NodePort
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: snappass-app
---
apiVersion: v1
kind: Service
metadata:
  name: snappass-canary-service
  namespace: snappass
spec:
  # type: NodePort
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: snappass-app
