apiVersion: v1
kind: Pod
metadata:
    labels:
        name: service1
    name: service1
    namespace: service1
spec:
    # replicas: 2
    # template:
    #     metadata:
    #         labels:
    #             app: service1
    #     spec:
    volumes: 
        - 
            name: data
            persistentVolumeClaim: 
                claimName: pvc1
    containers:
        -
            name: service1
            image: 'gcr.io/google-containers/busybox'
            command:
                - "sleep"
                - "6000"
            volumeMounts:
                -
                    name: data
                    mountPath: /mount
                    readOnly: false