apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: snappass-v2-deploy
  namespace: snappass
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: snappass-main
  template:
    metadata:
      labels:
        app: snappass-main
        version: v1.0.0
    spec:
      containers:
        - name: snappass-v2
          image: us.gcr.io/kuber-276115/snappass:v2.0.0
          imagePullPolicy: Always
          env:
            - name: REDIS_HOST
              value: snappass-redis
          ports:
            - containerPort: 5000
  strategy:
    blueGreen: # A new field for the Blue Green strategy options
      previewService: snappass-blue-service # Reference to a service
      activeService: snappass-main # Reference to a service
      autoPromotionEnabled: false
---
apiVersion: v1
kind: Service
metadata:
  name: snappass-blue-service
spec:
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app: snappass-main
    version: v2.0.0
